#!/bin/bash

cf set-env $APP_NAME EASEY_CAMD_SERVICES_API_KEY $CAMD_SERVICES_API_KEY
cf set-env $APP_NAME EASEY_CAMD_SERVICES_SECRET_TOKEN $CAMD_SERVICES_SECRET_TOKEN
cf set-env $APP_NAME EASEY_BULK_FILES_AWS_ACCESS_KEY_ID $BULK_FILES_AWS_ACCESS_KEY_ID
cf set-env $APP_NAME EASEY_BULK_FILES_AWS_SECRET_ACCESS_KEY $BULK_FILES_AWS_SECRET_ACCESS_KEY
