name: Deploy Package Workflow

on:
  workflow_dispatch

jobs:
  Test-Deployment:
    runs-on: ubuntu-latest
    environment:
      name: Test
      url: https://api.epa.gov/easey/test/camd-services/swagger
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables-noTag.sh TEST
        env:
          ENV_VAR_PREFIX: EASEY
      - name: Configure Env Vars (secrets)
        run: devops/scripts/$APP_NAME/configure-env-vars-secrets.sh
        env:
          S3_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          S3_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CAMD_SVCS_NON_PROD_API_KEY: ${{ secrets.CAMD_SVCS_NON_PROD_API_KEY }}
          CAMD_SERVICES_API_SECRET_TOKEN: ${{ secrets.API_SECRET_TOKEN }}


# FROM RELEASE/V1.0
# name: Deploy Package Workflow

# on:
#   workflow_dispatch:
#     inputs:
#       ENV:
#         description: 'Select the Environment to deploy to'
#         required: true
#         type: environment
#       PACKAGE:
#         description: 'Add package (default to latest)'
#         required: false
#         type: string
#         default: 'latest'

# jobs:
#   Deployment:
#     steps:
#       - uses: US-EPA-CAMD/devops/.github/workflows/reusable-release-workflow.yaml@master
#         with:
#           ENV: ${{ inputs.ENV }}
#           PACKAGE: ${{ inputs.PACKAGE }}
#       - name: Deployment
#         run: |
#           devops/scripts/deploy.sh
