name: Release Branch Workflow

on:
  push:
    branches: [release/*]
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  Build-Test-Package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Setup & Configure Node
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
          registry-url: https://npm.pkg.github.com/
          scope: '@us-epa-camd'
      - name: Configure Env Vars
        run: devops/scripts/environment-variables-noTag.sh
        env:
          ENV_VAR_PREFIX: EASEY
      - name: Build
        run: devops/scripts/yarn/build.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Unit Tests
        run: devops/scripts/yarn/unit-tests.sh
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Package App
        run: devops/scripts/package-artifact.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_STORAGE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_STORAGE_SECRET_ACCESS_KEY }}

  Test-Deployment:
    needs: Build-Test-Package
    runs-on: ubuntu-latest
    environment:
      name: Test
      url: https://api.epa.gov/easey/test/camd-services/swagger
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables-noTag.sh TEST
        env:
          ENV_VAR_PREFIX: EASEY
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ secrets.CF_TST_DEPLOYMENT_SVC }}
          CF_PASSWORD: ${{ secrets.CF_TST_DEPLOYMENT_SVC_PWD }}
      - name: Download Deployment Package
        run: devops/scripts/download-artifact.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_STORAGE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_STORAGE_SECRET_ACCESS_KEY }}
      - name: Init Application
        run: devops/scripts/cf-app-init.sh
      - name: Configure Env Vars (secrets)
        run: scripts/environment-variables-secrets.sh
        env:
          CAMD_SERVICES_API_KEY: ${{ secrets.API_KEY }}
          CAMD_SERVICES_SECRET_TOKEN: ${{ secrets.API_SECRET_TOKEN }}
          BULK_FILES_AWS_ACCESS_KEY_ID: ${{ secrets.BULK_FILES_AWS_ACCESS_KEY_ID }}
          BULK_FILES_AWS_SECRET_ACCESS_KEY: ${{ secrets.BULK_FILES_AWS_SECRET_ACCESS_KEY }}
      - name: Deployment
        run: devops/scripts/deploy.sh

  Performance-Deployment:
    needs: Build-Test-Package
    runs-on: ubuntu-latest
    environment:
      name: Performance
      url: https://api.epa.gov/easey/perf/camd-services/swagger
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables-noTag.sh PERF
        env:
          ENV_VAR_PREFIX: EASEY
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ secrets.CF_PERF_DEPLOYMENT_SVC }}
          CF_PASSWORD: ${{ secrets.CF_PERF_DEPLOYMENT_SVC_PWD }}
      - name: Download Deployment Package
        run: devops/scripts/download-artifact.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_STORAGE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_STORAGE_SECRET_ACCESS_KEY }}
      - name: Init Application
        run: devops/scripts/cf-app-init.sh
      - name: Configure Env Vars (secrets)
        run: scripts/environment-variables-secrets.sh
        env:
          CAMD_SERVICES_API_KEY: ${{ secrets.API_KEY }}
          CAMD_SERVICES_SECRET_TOKEN: ${{ secrets.API_SECRET_TOKEN }}
          BULK_FILES_AWS_ACCESS_KEY_ID: ${{ secrets.BULK_FILES_AWS_ACCESS_KEY_ID }}
          BULK_FILES_AWS_SECRET_ACCESS_KEY: ${{ secrets.BULK_FILES_AWS_SECRET_ACCESS_KEY }}
      - name: Deployment
        run: devops/scripts/deploy.sh

  Beta-Deployment:
    needs: Build-Test-Package
    runs-on: ubuntu-latest
    environment:
      name: Beta
      url: https://api.epa.gov/easey/beta/camd-services/swagger
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables-noTag.sh BETA
        env:
          ENV_VAR_PREFIX: EASEY
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ secrets.CF_BETA_DEPLOYMENT_SVC }}
          CF_PASSWORD: ${{ secrets.CF_BETA_DEPLOYMENT_SVC_PWD }}
      - name: Download Deployment Package
        run: devops/scripts/download-artifact.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_STORAGE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_STORAGE_SECRET_ACCESS_KEY }}
      - name: Init Application
        run: devops/scripts/cf-app-init.sh
      - name: Configure Env Vars (secrets)
        run: scripts/environment-variables-secrets.sh
        env:
          CAMD_SERVICES_API_KEY: ${{ secrets.API_KEY }}
          CAMD_SERVICES_SECRET_TOKEN: ${{ secrets.API_SECRET_TOKEN }}
          BULK_FILES_AWS_ACCESS_KEY_ID: ${{ secrets.BULK_FILES_AWS_ACCESS_KEY_ID }}
          BULK_FILES_AWS_SECRET_ACCESS_KEY: ${{ secrets.BULK_FILES_AWS_SECRET_ACCESS_KEY }}
      - name: Deployment
        run: devops/scripts/deploy.sh

  Stage-Deployment:
    needs: Build-Test-Package
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: https://api.epa.gov/easey/staging/camd-services/swagger
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables-noTag.sh STAGE
        env:
          ENV_VAR_PREFIX: EASEY
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ secrets.CF_STG_DEPLOYMENT_SVC }}
          CF_PASSWORD: ${{ secrets.CF_STG_DEPLOYMENT_SVC_PWD }}
      - name: Download Deployment Package
        run: devops/scripts/download-artifact.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_STORAGE_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_STORAGE_SECRET_ACCESS_KEY }}
      - name: Init Application
        run: devops/scripts/cf-app-init.sh
      - name: Configure Env Vars (secrets)
        run: scripts/environment-variables-secrets.sh
        env:
          CAMD_SERVICES_API_KEY: ${{ secrets.API_KEY }}
          CAMD_SERVICES_SECRET_TOKEN: ${{ secrets.API_SECRET_TOKEN }}
          BULK_FILES_AWS_ACCESS_KEY_ID: ${{ secrets.BULK_FILES_AWS_ACCESS_KEY_ID }}
          BULK_FILES_AWS_SECRET_ACCESS_KEY: ${{ secrets.BULK_FILES_AWS_SECRET_ACCESS_KEY }}
      - name: Deployment
        run: devops/scripts/deploy.sh

  # Prod-Deployment:
  #   needs: Build-Test-Package
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: Production
  #     url: https://api.epa.gov/easey/camd-services/swagger
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2
  #     - name: Checkout devops repo
  #       uses: actions/checkout@v2
  #       with:
  #         repository: US-EPA-CAMD/devops
  #         path: devops
  #     - name: Configure Env Vars
  #       run: devops/scripts/environment-variables-noTag.sh PROD
  #       env:
  #         ENV_VAR_PREFIX: EASEY
  #     - name: Install cf cli
  #       run: devops/scripts/install-cf-cli.sh
  #     - name: Login to cloud.gov
  #       run: devops/scripts/cf-login.sh
  #       env:
  #         CF_USERNAME: ${{ secrets.CF_PROD_DEPLOYMENT_SVC }}
  #         CF_PASSWORD: ${{ secrets.CF_PROD_DEPLOYMENT_SVC_PWD }}
  #     - name: Download Deployment Package
  #       run: devops/scripts/download-artifact.sh
  #       env:
  #         AWS_ACCESS_KEY_ID: ${{ secrets.ARTIFACTS_STORAGE_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.ARTIFACTS_STORAGE_SECRET_ACCESS_KEY }}
  #     - name: Init Application
  #       run: devops/scripts/cf-app-init.sh
  #     - name: Configure Env Vars (secrets)
  #       run: scripts/environment-variables-secrets.sh
  #       env:
  #         CAMD_SERVICES_API_KEY: ${{ secrets.API_KEY }}
  #         CAMD_SERVICES_SECRET_TOKEN: ${{ secrets.API_SECRET_TOKEN }}
  #         BULK_FILES_AWS_ACCESS_KEY_ID: ${{ secrets.BULK_FILES_AWS_ACCESS_KEY_ID }}
  #         BULK_FILES_AWS_SECRET_ACCESS_KEY: ${{ secrets.BULK_FILES_AWS_SECRET_ACCESS_KEY }}
  #     - name: Deployment
  #       run: devops/scripts/deploy.sh